version: '3.8'

services:
  backend:
    build:
      context: ./Python
      dockerfile: Dockerfile
    container_name: ats-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: ats-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
